// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: config.sql

package sqlcgen

import (
	"context"
)

const getSolverSettings = `-- name: GetSolverSettings :one
SELECT target_hours_per_week, shortfall_penalty, lead_shortfall_penalty,
       balance_penalty_weight, streak_penalty_weight, streak_length
FROM solver_settings
WHERE id = 1
`

type GetSolverSettingsRow struct {
	TargetHoursPerWeek   int32
	ShortfallPenalty     int32
	LeadShortfallPenalty int32
	BalancePenaltyWeight int32
	StreakPenaltyWeight  int32
	StreakLength         int32
}

func (q *Queries) GetSolverSettings(ctx context.Context) (GetSolverSettingsRow, error) {
	row := q.db.QueryRow(ctx, getSolverSettings)
	var i GetSolverSettingsRow
	err := row.Scan(
		&i.TargetHoursPerWeek,
		&i.ShortfallPenalty,
		&i.LeadShortfallPenalty,
		&i.BalancePenaltyWeight,
		&i.StreakPenaltyWeight,
		&i.StreakLength,
	)
	return i, err
}

const listGateShiftRequirements = `-- name: ListGateShiftRequirements :many
SELECT gate_code, shift_type, nv, lead, lead_mandatory_role, shift_hours
FROM gate_shift_requirements
`

func (q *Queries) ListGateShiftRequirements(ctx context.Context) ([]GateShiftRequirement, error) {
	rows, err := q.db.Query(ctx, listGateShiftRequirements)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GateShiftRequirement
	for rows.Next() {
		var i GateShiftRequirement
		if err := rows.Scan(
			&i.GateCode,
			&i.ShiftType,
			&i.Nv,
			&i.Lead,
			&i.LeadMandatoryRole,
			&i.ShiftHours,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGates = `-- name: ListGates :many
SELECT code, is_lead_gate FROM gates ORDER BY code
`

func (q *Queries) ListGates(ctx context.Context) ([]Gate, error) {
	rows, err := q.db.Query(ctx, listGates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Gate
	for rows.Next() {
		var i Gate
		if err := rows.Scan(&i.Code, &i.IsLeadGate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameGate = `-- name: RenameGate :execrows
UPDATE gates SET code = $2 WHERE code = $1
`

type RenameGateParams struct {
	Code   string
	Code_2 string
}

func (q *Queries) RenameGate(ctx context.Context, arg RenameGateParams) (int64, error) {
	result, err := q.db.Exec(ctx, renameGate, arg.Code, arg.Code_2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateGateShiftRequirement = `-- name: UpdateGateShiftRequirement :execrows
UPDATE gate_shift_requirements
SET nv = $3, lead = $4, lead_mandatory_role = $5, shift_hours = $6
WHERE gate_code = $1 AND shift_type = $2
`

type UpdateGateShiftRequirementParams struct {
	GateCode          string
	ShiftType         string
	Nv                int32
	Lead              int32
	LeadMandatoryRole bool
	ShiftHours        int32
}

func (q *Queries) UpdateGateShiftRequirement(ctx context.Context, arg UpdateGateShiftRequirementParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateGateShiftRequirement,
		arg.GateCode,
		arg.ShiftType,
		arg.Nv,
		arg.Lead,
		arg.LeadMandatoryRole,
		arg.ShiftHours,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
