// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: employee.sql

package sqlcgen

import (
	"context"
	"time"
)

const createEmployee = `-- name: CreateEmployee :one
INSERT INTO employees (employee_id, name, role, active)
VALUES ($1, $2, $3, TRUE)
RETURNING employee_id, name, role, active
`

type CreateEmployeeParams struct {
	EmployeeID string
	Name       string
	Role       string
}

type CreateEmployeeRow struct {
	EmployeeID string
	Name       string
	Role       string
	Active     bool
}

func (q *Queries) CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (CreateEmployeeRow, error) {
	row := q.db.QueryRow(ctx, createEmployee, arg.EmployeeID, arg.Name, arg.Role)
	var i CreateEmployeeRow
	err := row.Scan(
		&i.EmployeeID,
		&i.Name,
		&i.Role,
		&i.Active,
	)
	return i, err
}

const deleteLeaveDay = `-- name: DeleteLeaveDay :exec
DELETE FROM employee_leave_days WHERE employee_id = $1 AND leave_date = $2
`

type DeleteLeaveDayParams struct {
	EmployeeID string
	LeaveDate  time.Time
}

func (q *Queries) DeleteLeaveDay(ctx context.Context, arg DeleteLeaveDayParams) error {
	_, err := q.db.Exec(ctx, deleteLeaveDay, arg.EmployeeID, arg.LeaveDate)
	return err
}

const getAvailability = `-- name: GetAvailability :many
SELECT employee_id, avail_date, sang, dem
FROM employee_availability
WHERE avail_date BETWEEN $1::date AND $2::date
ORDER BY employee_id, avail_date
`

type GetAvailabilityParams struct {
	FromDate time.Time
	ToDate   time.Time
}

func (q *Queries) GetAvailability(ctx context.Context, arg GetAvailabilityParams) ([]EmployeeAvailability, error) {
	rows, err := q.db.Query(ctx, getAvailability, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmployeeAvailability
	for rows.Next() {
		var i EmployeeAvailability
		if err := rows.Scan(
			&i.EmployeeID,
			&i.AvailDate,
			&i.Sang,
			&i.Dem,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertLeaveDay = `-- name: InsertLeaveDay :exec
INSERT INTO employee_leave_days (employee_id, leave_date)
VALUES ($1, $2)
ON CONFLICT (employee_id, leave_date) DO NOTHING
`

type InsertLeaveDayParams struct {
	EmployeeID string
	LeaveDate  time.Time
}

func (q *Queries) InsertLeaveDay(ctx context.Context, arg InsertLeaveDayParams) error {
	_, err := q.db.Exec(ctx, insertLeaveDay, arg.EmployeeID, arg.LeaveDate)
	return err
}

const listEmployeeLeaveDays = `-- name: ListEmployeeLeaveDays :many
SELECT employee_id, leave_date
FROM employee_leave_days
ORDER BY employee_id, leave_date
`

func (q *Queries) ListEmployeeLeaveDays(ctx context.Context) ([]EmployeeLeaveDay, error) {
	rows, err := q.db.Query(ctx, listEmployeeLeaveDays)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmployeeLeaveDay
	for rows.Next() {
		var i EmployeeLeaveDay
		if err := rows.Scan(&i.EmployeeID, &i.LeaveDate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployees = `-- name: ListEmployees :many
SELECT employee_id, name, role, active
FROM employees
WHERE active OR $1::boolean
ORDER BY employee_id
`

type ListEmployeesRow struct {
	EmployeeID string
	Name       string
	Role       string
	Active     bool
}

func (q *Queries) ListEmployees(ctx context.Context, includeInactive bool) ([]ListEmployeesRow, error) {
	rows, err := q.db.Query(ctx, listEmployees, includeInactive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEmployeesRow
	for rows.Next() {
		var i ListEmployeesRow
		if err := rows.Scan(
			&i.EmployeeID,
			&i.Name,
			&i.Role,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setEmployeeActive = `-- name: SetEmployeeActive :one
UPDATE employees
SET active = $2, updated_at = now()
WHERE employee_id = $1
RETURNING employee_id, name, role, active
`

type SetEmployeeActiveParams struct {
	EmployeeID string
	Active     bool
}

type SetEmployeeActiveRow struct {
	EmployeeID string
	Name       string
	Role       string
	Active     bool
}

func (q *Queries) SetEmployeeActive(ctx context.Context, arg SetEmployeeActiveParams) (SetEmployeeActiveRow, error) {
	row := q.db.QueryRow(ctx, setEmployeeActive, arg.EmployeeID, arg.Active)
	var i SetEmployeeActiveRow
	err := row.Scan(
		&i.EmployeeID,
		&i.Name,
		&i.Role,
		&i.Active,
	)
	return i, err
}

const updateEmployee = `-- name: UpdateEmployee :one
UPDATE employees
SET name = $2, role = $3, updated_at = now()
WHERE employee_id = $1
RETURNING employee_id, name, role, active
`

type UpdateEmployeeParams struct {
	EmployeeID string
	Name       string
	Role       string
}

type UpdateEmployeeRow struct {
	EmployeeID string
	Name       string
	Role       string
	Active     bool
}

func (q *Queries) UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) (UpdateEmployeeRow, error) {
	row := q.db.QueryRow(ctx, updateEmployee, arg.EmployeeID, arg.Name, arg.Role)
	var i UpdateEmployeeRow
	err := row.Scan(
		&i.EmployeeID,
		&i.Name,
		&i.Role,
		&i.Active,
	)
	return i, err
}

const upsertAvailability = `-- name: UpsertAvailability :exec
INSERT INTO employee_availability (employee_id, avail_date, sang, dem)
VALUES ($1, $2, $3, $4)
ON CONFLICT (employee_id, avail_date) DO UPDATE SET sang = $3, dem = $4
`

type UpsertAvailabilityParams struct {
	EmployeeID string
	AvailDate  time.Time
	Sang       bool
	Dem        bool
}

func (q *Queries) UpsertAvailability(ctx context.Context, arg UpsertAvailabilityParams) error {
	_, err := q.db.Exec(ctx, upsertAvailability,
		arg.EmployeeID,
		arg.AvailDate,
		arg.Sang,
		arg.Dem,
	)
	return err
}
