// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type ApprovedAssignment struct {
	EmployeeID     string
	AssignmentDate time.Time
	Gate           *string
	Shift          *string
	Off            bool
	ApprovedAt     pgtype.Timestamptz
	ApprovedBy     string
}

type Employee struct {
	EmployeeID string
	Name       string
	Role       string
	Active     bool
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type EmployeeAvailability struct {
	EmployeeID string
	AvailDate  time.Time
	Sang       bool
	Dem        bool
}

type EmployeeLeaveDay struct {
	EmployeeID string
	LeaveDate  time.Time
}

type Gate struct {
	Code       string
	IsLeadGate bool
}

type GateShiftRequirement struct {
	GateCode          string
	ShiftType         string
	Nv                int32
	Lead              int32
	LeadMandatoryRole bool
	ShiftHours        int32
}

type ScheduleAssignment struct {
	ScheduleRunID  int64
	EmployeeID     string
	AssignmentDate time.Time
	Gate           string
	Shift          string
}

type ScheduleEmployeeSummary struct {
	ScheduleRunID  int64
	EmployeeID     string
	Role           string
	LeaveDays      int32
	TargetHours    int32
	ActualHours    int32
	DeviationHours int32
	ActualShifts   int32
}

type ScheduleRun struct {
	ID             int64
	StartDate      time.Time
	NumDays        int32
	Status         string
	ObjectiveValue *float64
	WallTimeS      float64
	CreatedAt      pgtype.Timestamptz
}

type ScheduleShortage struct {
	ID            int64
	ScheduleRunID int64
	ShortageDate  time.Time
	Gate          string
	Shift         string
	ShortageType  string
	Missing       int32
}

type SolverSetting struct {
	ID                   int32
	TargetHoursPerWeek   int32
	ShortfallPenalty     int32
	LeadShortfallPenalty int32
	BalancePenaltyWeight int32
	StreakPenaltyWeight  int32
	StreakLength         int32
	UpdatedAt            pgtype.Timestamptz
}
