// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schedule.sql

package sqlcgen

import (
	"context"
	"time"
)

const deleteApprovedAssignments = `-- name: DeleteApprovedAssignments :execrows
DELETE FROM approved_assignments
WHERE assignment_date BETWEEN $1 AND $2
`

type DeleteApprovedAssignmentsParams struct {
	AssignmentDate   time.Time
	AssignmentDate_2 time.Time
}

func (q *Queries) DeleteApprovedAssignments(ctx context.Context, arg DeleteApprovedAssignmentsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteApprovedAssignments, arg.AssignmentDate, arg.AssignmentDate_2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLatestScheduleRun = `-- name: GetLatestScheduleRun :one
SELECT id, start_date, num_days, status, objective_value, wall_time_s
FROM schedule_runs
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestScheduleRunRow struct {
	ID             int64
	StartDate      time.Time
	NumDays        int32
	Status         string
	ObjectiveValue *float64
	WallTimeS      float64
}

func (q *Queries) GetLatestScheduleRun(ctx context.Context) (GetLatestScheduleRunRow, error) {
	row := q.db.QueryRow(ctx, getLatestScheduleRun)
	var i GetLatestScheduleRunRow
	err := row.Scan(
		&i.ID,
		&i.StartDate,
		&i.NumDays,
		&i.Status,
		&i.ObjectiveValue,
		&i.WallTimeS,
	)
	return i, err
}

const hasApprovedAssignmentsOnDate = `-- name: HasApprovedAssignmentsOnDate :one
SELECT EXISTS(SELECT 1 FROM approved_assignments WHERE assignment_date = $1)
`

func (q *Queries) HasApprovedAssignmentsOnDate(ctx context.Context, assignmentDate time.Time) (bool, error) {
	row := q.db.QueryRow(ctx, hasApprovedAssignmentsOnDate, assignmentDate)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertScheduleRun = `-- name: InsertScheduleRun :one
INSERT INTO schedule_runs (start_date, num_days, status, objective_value, wall_time_s)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type InsertScheduleRunParams struct {
	StartDate      time.Time
	NumDays        int32
	Status         string
	ObjectiveValue *float64
	WallTimeS      float64
}

func (q *Queries) InsertScheduleRun(ctx context.Context, arg InsertScheduleRunParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertScheduleRun,
		arg.StartDate,
		arg.NumDays,
		arg.Status,
		arg.ObjectiveValue,
		arg.WallTimeS,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listApprovedAssignments = `-- name: ListApprovedAssignments :many
SELECT employee_id, assignment_date, gate, shift, off
FROM approved_assignments
WHERE assignment_date BETWEEN $1 AND $2
ORDER BY employee_id, assignment_date
`

type ListApprovedAssignmentsParams struct {
	AssignmentDate   time.Time
	AssignmentDate_2 time.Time
}

type ListApprovedAssignmentsRow struct {
	EmployeeID     string
	AssignmentDate time.Time
	Gate           *string
	Shift          *string
	Off            bool
}

func (q *Queries) ListApprovedAssignments(ctx context.Context, arg ListApprovedAssignmentsParams) ([]ListApprovedAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, listApprovedAssignments, arg.AssignmentDate, arg.AssignmentDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApprovedAssignmentsRow
	for rows.Next() {
		var i ListApprovedAssignmentsRow
		if err := rows.Scan(
			&i.EmployeeID,
			&i.AssignmentDate,
			&i.Gate,
			&i.Shift,
			&i.Off,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApprovedNightWorkers = `-- name: ListApprovedNightWorkers :many
SELECT employee_id FROM approved_assignments
WHERE assignment_date = $1 AND shift = 'dem' AND NOT off
`

func (q *Queries) ListApprovedNightWorkers(ctx context.Context, assignmentDate time.Time) ([]string, error) {
	rows, err := q.db.Query(ctx, listApprovedNightWorkers, assignmentDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var employee_id string
		if err := rows.Scan(&employee_id); err != nil {
			return nil, err
		}
		items = append(items, employee_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFallbackNightWorkers = `-- name: ListFallbackNightWorkers :many
SELECT sa.employee_id
FROM schedule_assignments sa
WHERE sa.assignment_date = $1 AND sa.shift = 'dem'
  AND sa.schedule_run_id = (SELECT id FROM schedule_runs ORDER BY created_at DESC LIMIT 1)
`

func (q *Queries) ListFallbackNightWorkers(ctx context.Context, assignmentDate time.Time) ([]string, error) {
	rows, err := q.db.Query(ctx, listFallbackNightWorkers, assignmentDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var employee_id string
		if err := rows.Scan(&employee_id); err != nil {
			return nil, err
		}
		items = append(items, employee_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduleAssignmentsByRun = `-- name: ListScheduleAssignmentsByRun :many
SELECT employee_id, assignment_date, gate, shift
FROM schedule_assignments
WHERE schedule_run_id = $1
ORDER BY employee_id, assignment_date
`

type ListScheduleAssignmentsByRunRow struct {
	EmployeeID     string
	AssignmentDate time.Time
	Gate           string
	Shift          string
}

func (q *Queries) ListScheduleAssignmentsByRun(ctx context.Context, scheduleRunID int64) ([]ListScheduleAssignmentsByRunRow, error) {
	rows, err := q.db.Query(ctx, listScheduleAssignmentsByRun, scheduleRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListScheduleAssignmentsByRunRow
	for rows.Next() {
		var i ListScheduleAssignmentsByRunRow
		if err := rows.Scan(
			&i.EmployeeID,
			&i.AssignmentDate,
			&i.Gate,
			&i.Shift,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduleEmployeeSummaryByRun = `-- name: ListScheduleEmployeeSummaryByRun :many
SELECT employee_id, role, leave_days, target_hours, actual_hours, deviation_hours, actual_shifts
FROM schedule_employee_summary
WHERE schedule_run_id = $1
ORDER BY employee_id
`

type ListScheduleEmployeeSummaryByRunRow struct {
	EmployeeID     string
	Role           string
	LeaveDays      int32
	TargetHours    int32
	ActualHours    int32
	DeviationHours int32
	ActualShifts   int32
}

func (q *Queries) ListScheduleEmployeeSummaryByRun(ctx context.Context, scheduleRunID int64) ([]ListScheduleEmployeeSummaryByRunRow, error) {
	rows, err := q.db.Query(ctx, listScheduleEmployeeSummaryByRun, scheduleRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListScheduleEmployeeSummaryByRunRow
	for rows.Next() {
		var i ListScheduleEmployeeSummaryByRunRow
		if err := rows.Scan(
			&i.EmployeeID,
			&i.Role,
			&i.LeaveDays,
			&i.TargetHours,
			&i.ActualHours,
			&i.DeviationHours,
			&i.ActualShifts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduleShortagesByRun = `-- name: ListScheduleShortagesByRun :many
SELECT shortage_date, gate, shift, shortage_type, missing
FROM schedule_shortages
WHERE schedule_run_id = $1
ORDER BY shortage_date, gate, shift
`

type ListScheduleShortagesByRunRow struct {
	ShortageDate time.Time
	Gate         string
	Shift        string
	ShortageType string
	Missing      int32
}

func (q *Queries) ListScheduleShortagesByRun(ctx context.Context, scheduleRunID int64) ([]ListScheduleShortagesByRunRow, error) {
	rows, err := q.db.Query(ctx, listScheduleShortagesByRun, scheduleRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListScheduleShortagesByRunRow
	for rows.Next() {
		var i ListScheduleShortagesByRunRow
		if err := rows.Scan(
			&i.ShortageDate,
			&i.Gate,
			&i.Shift,
			&i.ShortageType,
			&i.Missing,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
